// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ServiceCreateIn
 *
 * The schema the API actually accepts from the frontend.
 */
export type ServiceCreateIn = {
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    icon?: ServiceIcon;
    /**
     * Isactive
     */
    isActive?: boolean;
    /**
     * Shortdesc
     */
    shortDesc: string;
    /**
     * Description
     */
    description: string;
    /**
     * Features
     */
    features?: Array<string>;
    /**
     * Pricing
     */
    pricing?: Array<ServicePricing>;
    /**
     * Faqs
     */
    faqs?: Array<ServiceFaq>;
};

/**
 * ServiceFAQ
 */
export type ServiceFaq = {
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
};

/**
 * ServiceIcon
 */
export type ServiceIcon = 'CreditCard' | 'Smartphone' | 'Search' | 'Wrench';

/**
 * ServicePricing
 */
export type ServicePricing = {
    /**
     * Label
     */
    label: string;
    /**
     * Price
     */
    price: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ServiceRead
 */
export type ServiceRead = {
    /**
     * Title
     */
    title: string;
    /**
     * Slug
     */
    slug: string;
    icon?: ServiceIcon;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Short Desc
     */
    short_desc: string;
    /**
     * Description
     */
    description: string;
    /**
     * Features
     */
    features?: Array<string>;
    /**
     * Pricing
     */
    pricing?: Array<ServicePricing>;
    /**
     * Faqs
     */
    faqs?: Array<ServiceFaq>;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Tenant Id
     */
    tenant_id: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Full Name
     */
    full_name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type SyncUserApiV1UsersSyncPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/sync';
};

export type SyncUserApiV1UsersSyncPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type SyncUserApiV1UsersSyncPostResponse = SyncUserApiV1UsersSyncPostResponses[keyof SyncUserApiV1UsersSyncPostResponses];

export type ReadCurrentUserApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadCurrentUserApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadCurrentUserApiV1UsersMeGetResponse = ReadCurrentUserApiV1UsersMeGetResponses[keyof ReadCurrentUserApiV1UsersMeGetResponses];

export type UpdateCurrentUserApiV1UsersMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateCurrentUserApiV1UsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserApiV1UsersMePatchError = UpdateCurrentUserApiV1UsersMePatchErrors[keyof UpdateCurrentUserApiV1UsersMePatchErrors];

export type UpdateCurrentUserApiV1UsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateCurrentUserApiV1UsersMePatchResponse = UpdateCurrentUserApiV1UsersMePatchResponses[keyof UpdateCurrentUserApiV1UsersMePatchResponses];

export type ReadServicesApiV1ServicesGetServicesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Slug
         */
        slug?: string | null;
    };
    url: '/api/v1/services/get-services';
};

export type ReadServicesApiV1ServicesGetServicesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadServicesApiV1ServicesGetServicesGetError = ReadServicesApiV1ServicesGetServicesGetErrors[keyof ReadServicesApiV1ServicesGetServicesGetErrors];

export type ReadServicesApiV1ServicesGetServicesGetResponses = {
    /**
     * Response Read Services Api V1 Services Get Services Get
     *
     * Successful Response
     */
    200: Array<ServiceRead>;
};

export type ReadServicesApiV1ServicesGetServicesGetResponse = ReadServicesApiV1ServicesGetServicesGetResponses[keyof ReadServicesApiV1ServicesGetServicesGetResponses];

export type SeedServicesApiV1ServicesSeedServicesPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/services/seed-services';
};

export type SeedServicesApiV1ServicesSeedServicesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateServiceApiV1ServicesCreateServicePostData = {
    body: ServiceCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/services/create-service';
};

export type CreateServiceApiV1ServicesCreateServicePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateServiceApiV1ServicesCreateServicePostError = CreateServiceApiV1ServicesCreateServicePostErrors[keyof CreateServiceApiV1ServicesCreateServicePostErrors];

export type CreateServiceApiV1ServicesCreateServicePostResponses = {
    /**
     * Successful Response
     */
    200: ServiceRead;
};

export type CreateServiceApiV1ServicesCreateServicePostResponse = CreateServiceApiV1ServicesCreateServicePostResponses[keyof CreateServiceApiV1ServicesCreateServicePostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
